/**
 * BASE DE CONHECIMENTO & CATÁLOGO DE EDITAIS FISCAIS OFICIAIS
 *
 * Contém a árvore completa de disciplinas, tópicos de alta incidência,
 * pesagens oficiais e mapeamento para os maiores concursos fiscais do país.
 */

export interface FiscalTopicDefinition {
  id: string;
  name: string;
  kind: "topico" | "subtopico" | "conceito";
  depth: number;
  priority: number; // 1 a 5
  weight: number; // 1 a 10
  incidenceScore: number; // 0 a 100 (incidência histórica da banca)
  relevanceScore: number; // 0 a 100
  parentId?: string;
  prerequisiteId?: string;
  lawTags?: string[];
}

export interface FiscalSubjectDefinition {
  id: string;
  name: string;
  area: "Jurídica" | "Contábil & Auditoria" | "Exatas & TI" | "Básicas" | "Específica";
  isQuantitative: boolean;
  topics: FiscalTopicDefinition[];
}

export interface OfficialFiscalContest {
  id: string;
  name: string;
  organization: string;
  roleTitle: string;
  examBoard: "FGV" | "Cebraspe" | "FCC" | "Vunesp";
  status: "ativo" | "futuro" | "concluido";
  area: "Fiscal Estadual" | "Fiscal Federal" | "Fiscal Municipal";
  expectedVagas: number;
  salaryInitial: string;
  examDate: string; // Formato YYYY-MM-DD
  editalUrl?: string;
  description: string;
  highlights: string[];
  subjects: {
    subjectName: string;
    area: "Jurídica" | "Contábil & Auditoria" | "Exatas & TI" | "Básicas" | "Específica";
    isQuantitative: boolean;
    weight: number;
    questionsCount: number;
    incidence: string;
    topics: {
      name: string;
      priority: number;
      weight: number;
      incidenceScore: number;
      lawTags?: string[];
    }[];
  }[];
}

export const FISCAL_KNOWLEDGE_SUBJECTS: FiscalSubjectDefinition[] = [
  {
    id: "dir-tributario",
    name: "Direito Tributário",
    area: "Jurídica",
    isQuantitative: false,
    topics: [
      {
        id: "trib-stn-principios",
        name: "Sistema Tributário Nacional e Princípios Constitucionais Tributários",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 10,
        incidenceScore: 92,
        relevanceScore: 95,
        lawTags: ["CF/88 Art. 145 a 152", "Legalidade", "Anterioridade", "Capacidade Contributiva"],
      },
      {
        id: "trib-competencia-imunidades",
        name: "Competência Tributária e Imunidades Constitucionais",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 9,
        incidenceScore: 90,
        relevanceScore: 95,
        lawTags: ["CF/88 Art. 150 VI", "Imunidade Recíproca", "Templos", "Livros e Periódicos"],
      },
      {
        id: "trib-obrigacao-fato-gerador",
        name: "Obrigação Tributária: Fato Gerador, Sujeito Ativo e Passivo, Solidariedade",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 8,
        incidenceScore: 85,
        relevanceScore: 90,
        lawTags: ["CTN Art. 113 a 127", "Responsabilidade Tributária Art. 128 a 138"],
      },
      {
        id: "trib-credito-suspensao",
        name: "Crédito Tributário: Suspensão da Exigibilidade (Art. 151 CTN)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 10,
        incidenceScore: 95,
        relevanceScore: 98,
        lawTags: ["CTN Art. 151", "MODELAP", "Moratória", "Depósito", "Liminar"],
      },
      {
        id: "trib-credito-extincao",
        name: "Crédito Tributário: Extinção, Decadência e Prescrição (Art. 156 CTN)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 10,
        incidenceScore: 96,
        relevanceScore: 98,
        lawTags: ["CTN Art. 156", "Decadência Art. 173", "Prescrição Art. 174", "Súmulas STJ/STF"],
      },
      {
        id: "trib-credito-exclusao",
        name: "Crédito Tributário: Exclusão (Isenção e Anistia) e Garantias",
        kind: "topico",
        depth: 0,
        priority: 4,
        weight: 7,
        incidenceScore: 80,
        relevanceScore: 85,
        lawTags: ["CTN Art. 175 a 182", "Garantias e Privilégios Art. 183 a 193"],
      },
    ],
  },
  {
    id: "leg-trib-estadual",
    name: "Legislação Tributária Estadual (LTE)",
    area: "Específica",
    isQuantitative: false,
    topics: [
      {
        id: "lte-icms-lc87-fato-gerador",
        name: "ICMS — Incidência, Fato Gerador e Não Incidência (LC 87/96 - Lei Kandir)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 10,
        incidenceScore: 98,
        relevanceScore: 100,
        lawTags: ["LC 87/96 Art. 1º a 4º", "Circulação de Mercadorias", "Serviços de Transporte"],
      },
      {
        id: "lte-icms-base-calculo-aliquotas",
        name: "ICMS — Base de Cálculo, Inclusões/Exclusões, Alíquotas e DIFAL (LC 190/22)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 10,
        incidenceScore: 96,
        relevanceScore: 100,
        lawTags: ["LC 87/96 Art. 13", "DIFAL EC 87/15", "LC 190/22", "Frete e IPI na Base"],
      },
      {
        id: "lte-icms-nao-cumulatividade-creditos",
        name: "ICMS — Princípio da Não Cumulatividade, Créditos Básicos e Vedações/Estornos",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 10,
        incidenceScore: 95,
        relevanceScore: 100,
        lawTags: ["LC 87/96 Art. 19 a 23", "Ativo Permanente CIAP", "Uso e Consumo"],
      },
      {
        id: "lte-icms-substituicao-tributaria",
        name: "ICMS — Substituição Tributária (ST) e Antecipação (LC 87/96 e Convênio ICMS 142/18)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 10,
        incidenceScore: 94,
        relevanceScore: 98,
        lawTags: ["MVA Ajustada", "Substituição para Frente", "Ressarcimento do ICMS-ST"],
      },
      {
        id: "lte-ipva-itcmd",
        name: "IPVA e ITCMD — Fato Gerador, Imunidades, Contribuintes e Alíquotas",
        kind: "topico",
        depth: 0,
        priority: 4,
        weight: 7,
        incidenceScore: 78,
        relevanceScore: 85,
        lawTags: ["CF/88 Art. 155 I e III", "Reforma Tributária EC 132/23"],
      },
      {
        id: "lte-pat-processo-administrativo",
        name: "Processo Administrativo Tributário (PAT), Auto de Infração e Consulta Tributária",
        kind: "topico",
        depth: 0,
        priority: 4,
        weight: 8,
        incidenceScore: 82,
        relevanceScore: 90,
        lawTags: ["Notificação de Lançamento", "Julgamento Administrativo", "TIT-SP / CONSEF"],
      },
    ],
  },
  {
    id: "contabilidade-geral-avancada",
    name: "Contabilidade Geral e Avançada",
    area: "Contábil & Auditoria",
    isQuantitative: true,
    topics: [
      {
        id: "cont-cpc00-estrutura-conceitual",
        name: "CPC 00 (R2) — Estrutura Conceitual para Relatório Financeiro",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 9,
        incidenceScore: 90,
        relevanceScore: 95,
        lawTags: ["Características Qualitativas Fundamentais e de Melhoria", "Ativo, Passivo, PL"],
      },
      {
        id: "cont-cpc16-estoques",
        name: "CPC 16 — Estoques: Mensuração, PEPS, Média Ponderada e Valor Realizável Líquido",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 9,
        incidenceScore: 92,
        relevanceScore: 95,
        lawTags: [
          "Custo de Aquisição",
          "Tributos Recuperáveis vs Não Recuperáveis",
          "Ajuste a VRL",
        ],
      },
      {
        id: "cont-balanco-patrimonial-dre",
        name: "Demonstrações Contábeis: Balanço Patrimonial e DRE (Lei 6.404/76 e CPC 26)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 10,
        incidenceScore: 94,
        relevanceScore: 98,
        lawTags: ["Lei 6.404/76 Art. 178 a 188", "Classificação de Ativos e Passivos"],
      },
      {
        id: "cont-cpc03-dfc-dmpl",
        name: "Demonstração dos Fluxos de Caixa (CPC 03 - DFC) e DMPL (CPC 26)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 9,
        incidenceScore: 88,
        relevanceScore: 92,
        lawTags: ["Método Direto e Indireto", "Fluxo Operacional, Investimento e Financiamento"],
      },
      {
        id: "cont-cpc27-ativo-imobilizado-depreciacao",
        name: "CPC 27 — Ativo Imobilizado, Depreciação, Amortização e Redução ao Valor Recuperável (CPC 01)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 8,
        incidenceScore: 86,
        relevanceScore: 90,
        lawTags: ["Valor Residual", "Vida Útil Econômica", "Impairment Test"],
      },
      {
        id: "cont-cpc25-provisoes-passivos-contingentes",
        name: "CPC 25 — Provisões, Passivos Contingentes e Ativos Contingentes",
        kind: "topico",
        depth: 0,
        priority: 4,
        weight: 8,
        incidenceScore: 84,
        relevanceScore: 88,
        lawTags: ["Probabilidade: Provável, Possível, Remota", "Reconhecimento vs Divulgação"],
      },
      {
        id: "cont-cpc18-equivalencia-patrimonial",
        name: "CPC 18 — Método de Equivalência Patrimonial (MEP) e Combinação de Negócios (CPC 15)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 10,
        incidenceScore: 91,
        relevanceScore: 96,
        lawTags: ["Coligadas e Controladas", "Mais-Valia e Goodwill", "Consolidação de Balanços"],
      },
    ],
  },
  {
    id: "auditoria-fiscal",
    name: "Auditoria Fiscal e SPED",
    area: "Contábil & Auditoria",
    isQuantitative: false,
    topics: [
      {
        id: "aud-normas-nbcta-evidencias",
        name: "Normas de Auditoria (NBC TA 200/500): Procedimentos, Evidências e Documentação de Auditoria",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 9,
        incidenceScore: 91,
        relevanceScore: 95,
        lawTags: ["Inspeção, Observação, Recálculo, Confirmação Externa (Circularização)"],
      },
      {
        id: "aud-risco-amostragem-estatistica",
        name: "Risco de Auditoria (Inerente, Controle e Detecção) e Amostragem (NBC TA 530)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 8,
        incidenceScore: 88,
        relevanceScore: 92,
        lawTags: ["Matriz de Risco", "Erro Tolerável", "Amostragem Estatística vs Não Estatística"],
      },
      {
        id: "aud-sped-fiscal-efd",
        name: "SPED Fiscal — EFD ICMS/IPI, Bloco K (Controle de Produção e Estoque) e EFD-Contribuições",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 10,
        incidenceScore: 95,
        relevanceScore: 98,
        lawTags: ["Cruzamento de EFD vs NF-e", "Bloco C (Documentos Fiscais)", "Bloco K"],
      },
      {
        id: "aud-auditoria-contas-balanco",
        name: "Auditoria em Contas do Ativo, Passivo, Receitas e Despesas (Presunções Legais de Omissão de Receita)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 9,
        incidenceScore: 92,
        relevanceScore: 95,
        lawTags: [
          "Suprimento Indevido de Caixa",
          "Passivo Fictício",
          "Depósitos Bancários não Comprovados",
        ],
      },
    ],
  },
  {
    id: "ti-ciencia-dados-fiscal",
    name: "Tecnologia da Informação & Análise de Dados",
    area: "Exatas & TI",
    isQuantitative: true,
    topics: [
      {
        id: "ti-banco-dados-sql",
        name: "Modelagem de Dados Relacional e Consultas SQL Avançadas (SELECT, JOIN, GROUP BY, Subqueries)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 10,
        incidenceScore: 96,
        relevanceScore: 98,
        lawTags: ["DDL, DML, DQL", "Índices, Chaves Primárias e Estrangeiras", "ACID"],
      },
      {
        id: "ti-python-pandas-auditoria",
        name: "Ciência de Dados e Python para Auditoria (Manipulação de Dados com Pandas, NumPy)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 8,
        incidenceScore: 84,
        relevanceScore: 90,
        lawTags: ["Data Wrangling", "Detecção de Anomalias Fiscais", "ETL"],
      },
      {
        id: "ti-seguranca-lgpd",
        name: "Segurança da Informação (ISO 27001/27002), Criptografia, Assinatura Digital e LGPD (Lei 13.709/18)",
        kind: "topico",
        depth: 0,
        priority: 4,
        weight: 7,
        incidenceScore: 80,
        relevanceScore: 85,
        lawTags: [
          "Chaves Simétricas/Assimétricas",
          "Certificados ICP-Brasil",
          "Princípios da LGPD",
        ],
      },
      {
        id: "ti-big-data-nosql",
        name: "Big Data, Mineração de Dados, Data Warehouse e Bancos Não-Relacionais (NoSQL)",
        kind: "topico",
        depth: 0,
        priority: 4,
        weight: 7,
        incidenceScore: 78,
        relevanceScore: 84,
        lawTags: ["OLAP vs OLTP", "Star Schema / Snowflake", "Clustering e Classificação"],
      },
    ],
  },
  {
    id: "direito-administrativo",
    name: "Direito Administrativo",
    area: "Jurídica",
    isQuantitative: false,
    topics: [
      {
        id: "adm-atos-administrativos",
        name: "Atos Administrativos: Elementos, Atributos, Classificação, Anulação e Revogação",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 8,
        incidenceScore: 92,
        relevanceScore: 92,
        lawTags: ["COMFIFOR", "Autoexecutoriedade", "Tipicidade", "Súmula 473 STF"],
      },
      {
        id: "adm-licitacoes-lei14133",
        name: "Licitações e Contratos Administrativos (Nova Lei nº 14.133/21)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 9,
        incidenceScore: 95,
        relevanceScore: 96,
        lawTags: ["Modalidades de Licitação", "Contratação Direta: Inexigibilidade e Dispensa"],
      },
      {
        id: "adm-agentes-publicos-improbidade",
        name: "Agentes Públicos e Lei de Improbidade Administrativa (Lei 8.429/92 com alterações da Lei 14.230/21)",
        kind: "topico",
        depth: 0,
        priority: 4,
        weight: 7,
        incidenceScore: 86,
        relevanceScore: 88,
        lawTags: ["Exigência de Dolo Específico", "Enriquecimento Ilícito e Prejuízo ao Erário"],
      },
      {
        id: "adm-responsabilidade-civil",
        name: "Responsabilidade Civil do Estado e Processo Administrativo Federal (Lei 9.784/99)",
        kind: "topico",
        depth: 0,
        priority: 4,
        weight: 7,
        incidenceScore: 82,
        relevanceScore: 86,
        lawTags: [
          "CF/88 Art. 37 §6º",
          "Teoria do Risco Administrativo",
          "Excludentes de Responsabilidade",
        ],
      },
    ],
  },
  {
    id: "direito-constitucional",
    name: "Direito Constitucional",
    area: "Jurídica",
    isQuantitative: false,
    topics: [
      {
        id: "const-direitos-fundamentais",
        name: "Direitos e Garantias Fundamentais (Art. 5º da CF/88 e Remédios Constitucionais)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 8,
        incidenceScore: 90,
        relevanceScore: 90,
        lawTags: ["Habeas Data", "Mandado de Segurança", "Ação Popular", "Sigilo Bancário/Fiscal"],
      },
      {
        id: "const-organizacao-estado-poderes",
        name: "Organização do Estado, Repartição de Competências e Poder Executivo/Legislativo",
        kind: "topico",
        depth: 0,
        priority: 4,
        weight: 7,
        incidenceScore: 82,
        relevanceScore: 85,
        lawTags: [
          "CF/88 Art. 21 a 24",
          "Processo Legislativo",
          "Fiscalização Contábil e Financeira",
        ],
      },
      {
        id: "const-controle-constitucionalidade",
        name: "Controle de Constitucionalidade (Difuso e Concentrado: ADI, ADC, ADO e ADPF)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 8,
        incidenceScore: 88,
        relevanceScore: 92,
        lawTags: ["Legitimados do Art. 103 CF", "Efeitos Ex Tunc vs Modulação Temporal"],
      },
    ],
  },
  {
    id: "lingua-portuguesa",
    name: "Língua Portuguesa (Foco FGV)",
    area: "Básicas",
    isQuantitative: false,
    topics: [
      {
        id: "port-interpretacao-inferencia-fgv",
        name: "Interpretação e Compreensão de Texto, Inferência e Ambiguidade (Padrão FGV)",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 9,
        incidenceScore: 98,
        relevanceScore: 98,
        lawTags: ["Tipologia Textual", "Pressupostos e Subentendidos", "Semântica Textual"],
      },
      {
        id: "port-sintaxe-concordancia-regencia-crase",
        name: "Sintaxe do Período, Concordância Verbal/Nominal, Regência e Emprego do Sinal Indicativo de Crase",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 8,
        incidenceScore: 92,
        relevanceScore: 92,
        lawTags: ["Casos Obrigatórios e Proibidos de Crase", "Voz Passiva Sintética"],
      },
      {
        id: "port-coesao-pontuacao",
        name: "Coesão Textual, Conectivos, Paralelismo Sintático e Emprego dos Sinais de Pontuação",
        kind: "topico",
        depth: 0,
        priority: 4,
        weight: 7,
        incidenceScore: 88,
        relevanceScore: 90,
        lawTags: ["Uso da Vírgula entre Orações", "Pronomes Relativos e Anáfora"],
      },
    ],
  },
  {
    id: "rlm-estatistica",
    name: "Raciocínio Lógico e Estatística",
    area: "Exatas & TI",
    isQuantitative: true,
    topics: [
      {
        id: "rlm-logica-proposicional",
        name: "Lógica Proposicional: Conectivos, Tabelas-Verdade, Tautologia, Equivalências e Negações",
        kind: "topico",
        depth: 0,
        priority: 4,
        weight: 7,
        incidenceScore: 90,
        relevanceScore: 88,
        lawTags: ["Leis de De Morgan", "Condicional Se... Então", "Negação do Todo e Algum"],
      },
      {
        id: "rlm-matematica-financeira",
        name: "Matemática Financeira: Juros Simples e Compostos, Taxas Equivalentes, Descontos e VPL/TIR",
        kind: "topico",
        depth: 0,
        priority: 4,
        weight: 8,
        incidenceScore: 84,
        relevanceScore: 88,
        lawTags: ["Sistemas de Amortização SAC e Price", "Taxa Efetiva vs Nominal"],
      },
      {
        id: "est-probabilidade-inferencia",
        name: "Estatística Descritiva, Probabilidade, Distribuição Normal e Testes de Hipóteses",
        kind: "topico",
        depth: 0,
        priority: 5,
        weight: 9,
        incidenceScore: 88,
        relevanceScore: 92,
        lawTags: ["Média, Mediana, Variância e Desvio-Padrão", "Distribuição Binomial e Poisson"],
      },
    ],
  },
];

export const OFFICIAL_FISCAL_CONTESTS: OfficialFiscalContest[] = [
  {
    id: "sefaz-sp-afre",
    name: "SEFAZ-SP — Auditor Fiscal da Receita Estadual",
    organization: "Secretaria da Fazenda e Planejamento de São Paulo",
    roleTitle: "Auditor Fiscal da Receita Estadual (AFRE-SP)",
    examBoard: "FGV",
    status: "ativo",
    area: "Fiscal Estadual",
    expectedVagas: 500,
    salaryInitial: "R$ 24.500,00",
    examDate: "2026-11-22",
    description:
      "O edital de ouro dos fiscos estaduais. Peso máximo em Legislação Tributária de SP (ICMS), Contabilidade Avançada, Direito Tributário e Ciência de Dados/TI.",
    highlights: [
      "500 vagas autorizadas para Auditor Fiscal",
      "Banca FGV com questões complexas de casos práticos",
      "Salário inicial de R$ 24.500,00 + bônus de eficiência fiscal",
    ],
    subjects: [
      {
        subjectName: "Legislação Tributária Estadual (LTE)",
        area: "Específica",
        isQuantitative: false,
        weight: 5,
        questionsCount: 30,
        incidence: "Alta (25% dos pontos)",
        topics: [
          {
            name: "ICMS — Incidência, Fato Gerador e Não Incidência (LC 87/96 - Lei Kandir)",
            priority: 5,
            weight: 10,
            incidenceScore: 98,
          },
          {
            name: "ICMS — Base de Cálculo, Inclusões/Exclusões, Alíquotas e DIFAL (LC 190/22)",
            priority: 5,
            weight: 10,
            incidenceScore: 96,
          },
          {
            name: "ICMS — Princípio da Não Cumulatividade, Créditos Básicos e Vedações/Estornos",
            priority: 5,
            weight: 10,
            incidenceScore: 95,
          },
          {
            name: "ICMS — Substituição Tributária (ST) e Antecipação (LC 87/96 e Convênio ICMS 142/18)",
            priority: 5,
            weight: 10,
            incidenceScore: 94,
          },
          {
            name: "Processo Administrativo Tributário (PAT), Auto de Infração e Consulta Tributária",
            priority: 4,
            weight: 8,
            incidenceScore: 85,
          },
        ],
      },
      {
        subjectName: "Direito Tributário",
        area: "Jurídica",
        isQuantitative: false,
        weight: 5,
        questionsCount: 25,
        incidence: "Alta (20% dos pontos)",
        topics: [
          {
            name: "Crédito Tributário: Extinção, Decadência e Prescrição (Art. 156 CTN)",
            priority: 5,
            weight: 10,
            incidenceScore: 96,
          },
          {
            name: "Crédito Tributário: Suspensão da Exigibilidade (Art. 151 CTN)",
            priority: 5,
            weight: 10,
            incidenceScore: 95,
          },
          {
            name: "Sistema Tributário Nacional e Princípios Constitucionais Tributários",
            priority: 5,
            weight: 9,
            incidenceScore: 92,
          },
          {
            name: "Competência Tributária e Imunidades Constitucionais",
            priority: 5,
            weight: 9,
            incidenceScore: 90,
          },
        ],
      },
      {
        subjectName: "Contabilidade Geral e Avançada",
        area: "Contábil & Auditoria",
        isQuantitative: true,
        weight: 5,
        questionsCount: 25,
        incidence: "Alta (20% dos pontos)",
        topics: [
          {
            name: "Demonstrações Contábeis: Balanço Patrimonial e DRE (Lei 6.404/76 e CPC 26)",
            priority: 5,
            weight: 10,
            incidenceScore: 94,
          },
          {
            name: "CPC 18 — Método de Equivalência Patrimonial (MEP) e Combinação de Negócios (CPC 15)",
            priority: 5,
            weight: 10,
            incidenceScore: 91,
          },
          {
            name: "CPC 16 — Estoques: Mensuração, PEPS, Média Ponderada e Valor Realizável Líquido",
            priority: 5,
            weight: 9,
            incidenceScore: 92,
          },
          {
            name: "CPC 00 (R2) — Estrutura Conceitual para Relatório Financeiro",
            priority: 5,
            weight: 9,
            incidenceScore: 90,
          },
        ],
      },
      {
        subjectName: "Auditoria Fiscal e SPED",
        area: "Contábil & Auditoria",
        isQuantitative: false,
        weight: 4,
        questionsCount: 15,
        incidence: "Média (12% dos pontos)",
        topics: [
          {
            name: "SPED Fiscal — EFD ICMS/IPI, Bloco K (Controle de Produção e Estoque) e EFD-Contribuições",
            priority: 5,
            weight: 10,
            incidenceScore: 95,
          },
          {
            name: "Auditoria em Contas do Ativo, Passivo, Receitas e Despesas (Presunções Legais de Omissão de Receita)",
            priority: 5,
            weight: 9,
            incidenceScore: 92,
          },
          {
            name: "Normas de Auditoria (NBC TA 200/500): Procedimentos, Evidências e Documentação de Auditoria",
            priority: 5,
            weight: 9,
            incidenceScore: 91,
          },
        ],
      },
      {
        subjectName: "Tecnologia da Informação & Análise de Dados",
        area: "Exatas & TI",
        isQuantitative: true,
        weight: 4,
        questionsCount: 15,
        incidence: "Média (12% dos pontos)",
        topics: [
          {
            name: "Modelagem de Dados Relacional e Consultas SQL Avançadas (SELECT, JOIN, GROUP BY, Subqueries)",
            priority: 5,
            weight: 10,
            incidenceScore: 96,
          },
          {
            name: "Ciência de Dados e Python para Auditoria (Manipulação de Dados com Pandas, NumPy)",
            priority: 4,
            weight: 8,
            incidenceScore: 84,
          },
        ],
      },
      {
        subjectName: "Língua Portuguesa (Foco FGV)",
        area: "Básicas",
        isQuantitative: false,
        weight: 3,
        questionsCount: 15,
        incidence: "Base (11% dos pontos)",
        topics: [
          {
            name: "Interpretação e Compreensão de Texto, Inferência e Ambiguidade (Padrão FGV)",
            priority: 5,
            weight: 9,
            incidenceScore: 98,
          },
          {
            name: "Sintaxe do Período, Concordância Verbal/Nominal, Regência e Emprego do Sinal Indicativo de Crase",
            priority: 4,
            weight: 8,
            incidenceScore: 92,
          },
        ],
      },
    ],
  },
  {
    id: "rfb-auditor",
    name: "Receita Federal (RFB) — Auditor-Fiscal",
    organization: "Receita Federal do Brasil / Ministério da Fazenda",
    roleTitle: "Auditor-Fiscal da Receita Federal do Brasil (AFRFB)",
    examBoard: "FGV",
    status: "futuro",
    area: "Fiscal Federal",
    expectedVagas: 300,
    salaryInitial: "R$ 22.921,71",
    examDate: "2027-03-21",
    description:
      "Maior concurso fiscal da União. Conteúdo de Direito Tributário Federal, Contabilidade Geral/Avançada, Legislação Aduaneira e Comércio Internacional.",
    highlights: [
      "Concurso de âmbito nacional para atuação em fronteiras e superintendências",
      "Exigência profunda de Legislação Tributária Federal e Aduaneira",
      "Remuneração com bônus de eficiência e progressão rápida",
    ],
    subjects: [
      {
        subjectName: "Direito Tributário",
        area: "Jurídica",
        isQuantitative: false,
        weight: 5,
        questionsCount: 30,
        incidence: "Alta (25%)",
        topics: [
          {
            name: "Crédito Tributário: Extinção, Decadência e Prescrição (Art. 156 CTN)",
            priority: 5,
            weight: 10,
            incidenceScore: 96,
          },
          {
            name: "Crédito Tributário: Suspensão da Exigibilidade (Art. 151 CTN)",
            priority: 5,
            weight: 10,
            incidenceScore: 95,
          },
          {
            name: "Sistema Tributário Nacional e Princípios Constitucionais Tributários",
            priority: 5,
            weight: 9,
            incidenceScore: 92,
          },
        ],
      },
      {
        subjectName: "Contabilidade Geral e Avançada",
        area: "Contábil & Auditoria",
        isQuantitative: true,
        weight: 5,
        questionsCount: 20,
        incidence: "Alta (20%)",
        topics: [
          {
            name: "Demonstrações Contábeis: Balanço Patrimonial e DRE (Lei 6.404/76 e CPC 26)",
            priority: 5,
            weight: 10,
            incidenceScore: 94,
          },
          {
            name: "CPC 18 — Método de Equivalência Patrimonial (MEP) e Combinação de Negócios (CPC 15)",
            priority: 5,
            weight: 10,
            incidenceScore: 91,
          },
          {
            name: "CPC 03 — DFC e Demonstração do Valor Adicionado",
            priority: 4,
            weight: 8,
            incidenceScore: 88,
          },
        ],
      },
      {
        subjectName: "Auditoria Fiscal e SPED",
        area: "Contábil & Auditoria",
        isQuantitative: false,
        weight: 4,
        questionsCount: 15,
        incidence: "Média (15%)",
        topics: [
          {
            name: "Normas de Auditoria (NBC TA 200/500): Procedimentos, Evidências e Documentação de Auditoria",
            priority: 5,
            weight: 9,
            incidenceScore: 91,
          },
          {
            name: "Risco de Auditoria (Inerente, Controle e Detecção) e Amostragem (NBC TA 530)",
            priority: 4,
            weight: 8,
            incidenceScore: 88,
          },
        ],
      },
      {
        subjectName: "Tecnologia da Informação & Análise de Dados",
        area: "Exatas & TI",
        isQuantitative: true,
        weight: 4,
        questionsCount: 15,
        incidence: "Média (15%)",
        topics: [
          {
            name: "Modelagem de Dados Relacional e Consultas SQL Avançadas (SELECT, JOIN, GROUP BY, Subqueries)",
            priority: 5,
            weight: 10,
            incidenceScore: 96,
          },
          {
            name: "Ciência de Dados e Python para Auditoria (Manipulação de Dados com Pandas, NumPy)",
            priority: 4,
            weight: 8,
            incidenceScore: 84,
          },
        ],
      },
      {
        subjectName: "Língua Portuguesa (Foco FGV)",
        area: "Básicas",
        isQuantitative: false,
        weight: 3,
        questionsCount: 15,
        incidence: "Base (13%)",
        topics: [
          {
            name: "Interpretação e Compreensão de Texto, Inferência e Ambiguidade (Padrão FGV)",
            priority: 5,
            weight: 9,
            incidenceScore: 98,
          },
        ],
      },
    ],
  },
  {
    id: "sefaz-rj-afre",
    name: "SEFAZ-RJ — Auditor Fiscal da Receita Estadual",
    organization: "Secretaria de Estado de Fazenda do Rio de Janeiro",
    roleTitle: "Auditor Fiscal da Receita Estadual (AFRE-RJ)",
    examBoard: "Cebraspe",
    status: "ativo",
    area: "Fiscal Estadual",
    expectedVagas: 195,
    salaryInitial: "R$ 27.430,00",
    examDate: "2026-10-18",
    description:
      "Um dos mais bem remunerados fiscos estaduais do Brasil. Banca Cebraspe com forte ênfase no ICMS-RJ, Petróleo/Royalties, Direito Tributário e Contabilidade.",
    highlights: [
      "195 vagas autorizadas e edital em fase de publicação",
      "Remuneração no topo das carreiras fiscais estaduais",
      "Forte presença de Contabilidade Avançada e Auditoria Digital",
    ],
    subjects: [
      {
        subjectName: "Legislação Tributária Estadual (LTE)",
        area: "Específica",
        isQuantitative: false,
        weight: 5,
        questionsCount: 35,
        incidence: "Alta (28%)",
        topics: [
          {
            name: "ICMS — Incidência, Fato Gerador e Não Incidência (LC 87/96 - Lei Kandir)",
            priority: 5,
            weight: 10,
            incidenceScore: 98,
          },
          {
            name: "ICMS — Substituição Tributária (ST) e Antecipação (LC 87/96 e Convênio ICMS 142/18)",
            priority: 5,
            weight: 10,
            incidenceScore: 94,
          },
          {
            name: "IPVA e ITCMD — Fato Gerador, Imunidades, Contribuintes e Alíquotas",
            priority: 4,
            weight: 8,
            incidenceScore: 82,
          },
        ],
      },
      {
        subjectName: "Direito Tributário",
        area: "Jurídica",
        isQuantitative: false,
        weight: 5,
        questionsCount: 25,
        incidence: "Alta (20%)",
        topics: [
          {
            name: "Crédito Tributário: Extinção, Decadência e Prescrição (Art. 156 CTN)",
            priority: 5,
            weight: 10,
            incidenceScore: 96,
          },
          {
            name: "Crédito Tributário: Suspensão da Exigibilidade (Art. 151 CTN)",
            priority: 5,
            weight: 10,
            incidenceScore: 95,
          },
        ],
      },
      {
        subjectName: "Contabilidade Geral e Avançada",
        area: "Contábil & Auditoria",
        isQuantitative: true,
        weight: 5,
        questionsCount: 25,
        incidence: "Alta (20%)",
        topics: [
          {
            name: "Demonstrações Contábeis: Balanço Patrimonial e DRE (Lei 6.404/76 e CPC 26)",
            priority: 5,
            weight: 10,
            incidenceScore: 94,
          },
          {
            name: "CPC 18 — Método de Equivalência Patrimonial (MEP) e Combinação de Negócios (CPC 15)",
            priority: 5,
            weight: 10,
            incidenceScore: 91,
          },
        ],
      },
      {
        subjectName: "Auditoria Fiscal e SPED",
        area: "Contábil & Auditoria",
        isQuantitative: false,
        weight: 4,
        questionsCount: 15,
        incidence: "Média (15%)",
        topics: [
          {
            name: "SPED Fiscal — EFD ICMS/IPI, Bloco K (Controle de Produção e Estoque) e EFD-Contribuições",
            priority: 5,
            weight: 10,
            incidenceScore: 95,
          },
        ],
      },
    ],
  },
  {
    id: "iss-sp-aftm",
    name: "ISS-SP — Auditor Fiscal Tributário Municipal",
    organization: "Prefeitura de São Paulo / Secretaria da Fazenda Municipal",
    roleTitle: "Auditor Fiscal Tributário Municipal (AFTM-SP)",
    examBoard: "Vunesp",
    status: "futuro",
    area: "Fiscal Municipal",
    expectedVagas: 120,
    salaryInitial: "R$ 26.000,00",
    examDate: "2026-09-20",
    description:
      "O maior fisco municipal do país. Foco absoluto em ISS (LC 116/03), IPTU, ITBI, Direito Tributário e Contabilidade.",
    highlights: [
      "120 vagas estimadas para a capital paulista",
      "Remuneração inicial no teto salarial municipal",
      "Excelente qualidade de vida e rotina de fiscalização de serviços e tecnologia",
    ],
    subjects: [
      {
        subjectName: "Legislação Tributária Municipal (ISS/IPTU/ITBI)",
        area: "Específica",
        isQuantitative: false,
        weight: 5,
        questionsCount: 35,
        incidence: "Alta (30%)",
        topics: [
          {
            name: "ISS — Lei Complementar Federal nº 116/03 (Incidência, Não-Incidência, Local da Prestação e Alíquotas)",
            priority: 5,
            weight: 10,
            incidenceScore: 98,
          },
          {
            name: "IPTU e ITBI — Fato Gerador, Base de Cálculo (Planta Genérica de Valores), Imunidades e Isenções",
            priority: 5,
            weight: 9,
            incidenceScore: 94,
          },
        ],
      },
      {
        subjectName: "Direito Tributário",
        area: "Jurídica",
        isQuantitative: false,
        weight: 5,
        questionsCount: 25,
        incidence: "Alta (22%)",
        topics: [
          {
            name: "Competência Tributária e Imunidades Constitucionais",
            priority: 5,
            weight: 9,
            incidenceScore: 90,
          },
          {
            name: "Crédito Tributário: Extinção, Decadência e Prescrição (Art. 156 CTN)",
            priority: 5,
            weight: 10,
            incidenceScore: 96,
          },
        ],
      },
      {
        subjectName: "Contabilidade Geral e Avançada",
        area: "Contábil & Auditoria",
        isQuantitative: true,
        weight: 4,
        questionsCount: 20,
        incidence: "Alta (18%)",
        topics: [
          {
            name: "Demonstrações Contábeis: Balanço Patrimonial e DRE (Lei 6.404/76 e CPC 26)",
            priority: 5,
            weight: 10,
            incidenceScore: 94,
          },
        ],
      },
    ],
  },
];
