/**
 * REPOSITÓRIO DETERMINÍSTICO DE FONTES JURÍDICAS — BASE DE LEGISLAÇÃO E JURISPRUDÊNCIA (Fase 7.3.2)
 *
 * Contém a base nativa de fontes jurídicas tributárias e fiscais validadas,
 * permitindo buscas determinísticas por tópico, artigo, conceito, palavra-chave
 * ou integração com a tabela `sources` do Supabase.
 */

import type { LegalSource } from "./types";

/**
 * Base nativa e auditada de fontes jurídicas do Direito Tributário e Legislação Fiscal.
 */
export const VERIFIED_LEGAL_SOURCES_REPOSITORY: LegalSource[] = [
  {
    sourceId: "SRC_CF88_150",
    sourceType: "CONSTITUICAO",
    title: "Constituição Federal de 1988 — Limitações ao Poder de Tributar",
    jurisdiction: "Federal",
    authority: "Assembléia Nacional Constituinte",
    documentIdentifier: "CF/88",
    article: "Art. 150",
    paragraph: "inciso III",
    inciso: "III",
    text: "Sem prejuízo de outras garantias asseguradas ao contribuinte, é vedado à União, aos Estados, ao Distrito Federal e aos Municípios: III - cobrar tributos: a) em relação a fatos geradores ocorridos antes do início da vigência da lei que os houver instituído ou aumentado; b) no mesmo exercício financeiro em que haja sido publicada a lei que os instituiu ou aumentou; c) decorridos noventa dias da data em que haja sido publicada a lei que os instituiu ou aumentou.",
    effectiveDate: "1988-10-05",
    version: "1.0",
    validityStatus: "VIGENTE",
    topicIds: [
      "t_princípios",
      "t_principio_legalidade",
      "t_anterioridade",
      "t_limitações_tributar",
      "topico_principios",
    ],
    subjectName: "Direito Tributário",
    keywords: [
      "anterioridade",
      "irretroatividade",
      "fato gerador",
      "exercício financeiro",
      "noventena",
      "princípios tributários",
    ],
    reliability: 1.0,
  },
  {
    sourceId: "SRC_CTN_3",
    sourceType: "CTN",
    title: "Código Tributário Nacional — Conceito de Tributo",
    jurisdiction: "Federal",
    authority: "Congresso Nacional",
    documentIdentifier: "Lei 5.172/1966",
    article: "Art. 3º",
    text: "Tributo é toda prestação pecuniária compulsória, em moeda ou cujo valor nela se possa exprimir, que não constitua sanção de ato ilícito, instituída em lei e cobrada mediante atividade administrativa plenamente vinculada.",
    effectiveDate: "1966-10-25",
    version: "1.0",
    validityStatus: "VIGENTE",
    topicIds: ["t_conceito_tributo", "t_especies_tributarias", "topico_tributo"],
    subjectName: "Direito Tributário",
    keywords: [
      "conceito de tributo",
      "prestação pecuniária",
      "compulsória",
      "não constitua sanção",
      "atividade vinculada",
    ],
    reliability: 1.0,
  },
  {
    sourceId: "SRC_CTN_113",
    sourceType: "CTN",
    title: "Código Tributário Nacional — Obrigação Tributária Principal e Acessória",
    jurisdiction: "Federal",
    authority: "Congresso Nacional",
    documentIdentifier: "Lei 5.172/1966",
    article: "Art. 113",
    text: "A obrigação tributária é principal ou acessória. § 1º A obrigação principal surge com a ocorrência do fato gerador, tem por objeto o pagamento de tributo ou penalidade pecuniária e extingue-se juntamente com o crédito dela decorrente. § 2º A obrigação acessória decorre da legislação tributária e tem por objeto as prestações, positivas ou negativas, nela previstas no interesse da arrecadação ou da fiscalização dos tributos.",
    effectiveDate: "1966-10-25",
    version: "1.0",
    validityStatus: "VIGENTE",
    topicIds: ["t_obrigacao_tributaria", "t_fato_gerador", "topico_obrigacao"],
    subjectName: "Direito Tributário",
    keywords: [
      "obrigação tributária",
      "obrigação principal",
      "obrigação acessória",
      "fato gerador",
      "prestação positiva",
      "prestação negativa",
    ],
    reliability: 1.0,
  },
  {
    sourceId: "SRC_CTN_142",
    sourceType: "CTN",
    title: "Código Tributário Nacional — Conceito de Lançamento Tributário",
    jurisdiction: "Federal",
    authority: "Congresso Nacional",
    documentIdentifier: "Lei 5.172/1966",
    article: "Art. 142",
    text: "Compete privativamente à autoridade administrativa constituir o crédito tributário pelo lançamento, assim entendido o procedimento administrativo tendente a verificar a ocorrência do fato gerador da obrigação correspondente, determinar a matéria tributável, calcular o montante do tributo devido, identificar o sujeito passivo e, sendo caso, propor a aplicação da penalidade cabível.",
    effectiveDate: "1966-10-25",
    version: "1.0",
    validityStatus: "VIGENTE",
    topicIds: [
      "t_lancamento_tributario",
      "t_credito_tributario",
      "topico_lancamento",
      "topico_credito",
    ],
    subjectName: "Direito Tributário",
    keywords: [
      "lançamento tributário",
      "crédito tributário",
      "autoridade administrativa",
      "matéria tributável",
      "sujeito passivo",
    ],
    reliability: 1.0,
  },
  {
    sourceId: "SRC_CTN_149",
    sourceType: "CTN",
    title: "Código Tributário Nacional — Lançamento de Ofício ou Direto",
    jurisdiction: "Federal",
    authority: "Congresso Nacional",
    documentIdentifier: "Lei 5.172/1966",
    article: "Art. 149",
    text: "O lançamento é efetuado e revisto de ofício pela autoridade administrativa nos seguintes casos: I - quando a lei assim o determine; II - quando a declaração não seja prestada, por quem de direito, no prazo e na forma da legislação tributária; ... V - quando se comprove omissão ou inexatidão, por parte da pessoa que deva prestar a declaração.",
    effectiveDate: "1966-10-25",
    version: "1.0",
    validityStatus: "VIGENTE",
    topicIds: [
      "t_lancamento_oficio",
      "t_modalidades_lancamento",
      "t_lancamento_tributario",
      "topico_lancamento",
    ],
    subjectName: "Direito Tributário",
    keywords: [
      "lançamento de ofício",
      "lançamento direto",
      "fisco",
      "IPTU",
      "IPVA",
      "declaração omissa",
    ],
    reliability: 1.0,
  },
  {
    sourceId: "SRC_CTN_150",
    sourceType: "CTN",
    title: "Código Tributário Nacional — Lançamento por Homologação",
    jurisdiction: "Federal",
    authority: "Congresso Nacional",
    documentIdentifier: "Lei 5.172/1966",
    article: "Art. 150",
    paragraph: "§ 1º e § 4º",
    text: "O lançamento por homologação, que ocorre quanto aos tributos cuja legislação atribua ao sujeito passivo o dever de antecipar o pagamento sem prévio exame da autoridade administrativa, opera-se pelo ato em que referida autoridade, tomando conhecimento da atividade assim exercida pelo obrigado, expressamente a homologa. § 4º Se a lei não fixar prazo à homologação, será ele de cinco anos, a contar da ocorrência do fato gerador; expirado esse prazo sem que a Fazenda Pública se tenha pronunciado, considera-se homologado o lançamento e definitivamente extinto o crédito.",
    effectiveDate: "1966-10-25",
    version: "1.0",
    validityStatus: "VIGENTE",
    topicIds: [
      "t_lancamento_homologacao",
      "t_modalidades_lancamento",
      "t_lancamento_tributario",
      "topico_lancamento",
      "topico_homologacao",
    ],
    subjectName: "Direito Tributário",
    keywords: [
      "lançamento por homologação",
      "autolançamento",
      "pagamento antecipado",
      "homologação tácita",
      "prazo decadencial",
      "IRPF",
      "ICMS",
    ],
    reliability: 1.0,
  },
  {
    sourceId: "SRC_CTN_156",
    sourceType: "CTN",
    title: "Código Tributário Nacional — Modalidades de Extinção do Crédito Tributário",
    jurisdiction: "Federal",
    authority: "Congresso Nacional",
    documentIdentifier: "Lei 5.172/1966",
    article: "Art. 156",
    text: "Extinguem o crédito tributário: I - o pagamento; II - a compensação; III - a transação; IV - remissão; V - a prescrição e a decadência; VI - a conversão de depósito em renda; VII - o pagamento antecipado e a homologação do lançamento nos termos do art. 150; VIII - a consignação em pagamento; IX - a decisão administrativa irreformável; X - a decisão judicial passada em julgado; XI - a dação em pagamento em bens imóveis.",
    effectiveDate: "1966-10-25",
    version: "1.0",
    validityStatus: "VIGENTE",
    topicIds: ["t_extincao_credito", "t_decadencia_prescricao", "topico_credito"],
    subjectName: "Direito Tributário",
    keywords: [
      "extinção do crédito",
      "pagamento",
      "compensação",
      "prescrição",
      "decadência",
      "transação",
      "remissão",
      "dação em pagamento",
    ],
    reliability: 1.0,
  },
  {
    sourceId: "SRC_CTN_174",
    sourceType: "CTN",
    title: "Código Tributário Nacional — Prescrição da Ação de Cobrança do Crédito",
    jurisdiction: "Federal",
    authority: "Congresso Nacional",
    documentIdentifier: "Lei 5.172/1966",
    article: "Art. 174",
    text: "A ação para a cobrança do crédito tributário prescreve em cinco anos, contados da data da sua constituição definitiva. Parágrafo único. A prescrição se interrompe: I - pelo despacho do juiz que ordenar a citação em execução fiscal; II - pela protesto judicial; III - por qualquer ato judicial que constitua em mora o devedor; IV - por qualquer ato inequívoco ainda que extrajudicial, que importe em reconhecimento do débito pelo devedor.",
    effectiveDate: "1966-10-25",
    version: "1.0",
    validityStatus: "VIGENTE",
    topicIds: ["t_prescricao_tributaria", "t_decadencia_prescricao", "topico_prescricao"],
    subjectName: "Direito Tributário",
    keywords: [
      "prescrição tributária",
      "5 anos",
      "constituição definitiva",
      "interrupção da prescrição",
      "execução fiscal",
    ],
    reliability: 1.0,
  },
  {
    sourceId: "SRC_SV_50",
    sourceType: "SUMULA_VINCULANTE",
    title: "Súmula Vinculante 50 STF — Alteração de Prazo de Recolhimento",
    jurisdiction: "Federal",
    authority: "Supremo Tribunal Federal",
    documentIdentifier: "Súmula Vinculante 50",
    article: "Enunciado Único",
    text: "Norma legal que altera o prazo de recolhimento de obrigação tributária não se sujeita ao princípio da anterioridade.",
    effectiveDate: "2015-06-24",
    version: "1.0",
    validityStatus: "VIGENTE",
    topicIds: ["t_anterioridade", "t_princípios", "t_sumulas_stf", "topico_principios"],
    subjectName: "Direito Tributário",
    keywords: [
      "Súmula Vinculante 50",
      "prazo de recolhimento",
      "anterioridade",
      "vencimento da obrigação",
    ],
    reliability: 1.0,
  },
  {
    sourceId: "SRC_STJ_392",
    sourceType: "SUMULA",
    title: "Súmula 392 STJ — Substituição da Certidão de Dívida Ativa (CDA)",
    jurisdiction: "Federal",
    authority: "Superior Tribunal de Justiça",
    documentIdentifier: "Súmula 392 STJ",
    article: "Enunciado Único",
    text: "A Fazenda Pública pode substituir a certidão de dívida ativa (CDA) até a prolação da sentença de embargos, quando se tratar de erro material ou formal, vedada a modificação do sujeito passivo da execução.",
    effectiveDate: "2009-10-07",
    version: "1.0",
    validityStatus: "VIGENTE",
    topicIds: ["t_execucao_fiscal", "t_divida_ativa", "t_sumulas_stj", "topico_divida_ativa"],
    subjectName: "Direito Tributário",
    keywords: [
      "Súmula 392 STJ",
      "CDA",
      "Certidão de Dívida Ativa",
      "substituição",
      "sujeito passivo",
      "erro material",
    ],
    reliability: 1.0,
  },
  {
    sourceId: "SRC_LC_116_1",
    sourceType: "LEI_COMPLEMENTAR",
    title: "Lei Complementar 116/2003 — Imposto Sobre Serviços (ISS)",
    jurisdiction: "Federal",
    authority: "Congresso Nacional",
    documentIdentifier: "LC 116/2003",
    article: "Art. 1º",
    text: "O Imposto Sobre Serviços de Qualquer Natureza, de competência dos Municípios e do Distrito Federal, tem como fato gerador a prestação de serviços constantes da lista anexa, ainda que esses não se constituam como atividade preponderante do prestador.",
    effectiveDate: "2003-07-31",
    version: "1.0",
    validityStatus: "VIGENTE",
    topicIds: ["t_iss", "t_impostos_municipais", "topico_iss"],
    subjectName: "Legislação Tributária",
    keywords: [
      "ISS",
      "ISSQN",
      "LC 116/03",
      "fato gerador do ISS",
      "prestação de serviços",
      "impostos municipais",
    ],
    reliability: 1.0,
  },
  {
    sourceId: "SRC_LC_87_2",
    sourceType: "LEI_COMPLEMENTAR",
    title: "Lei Complementar 87/1996 (Lei Kandir) — ICMS Fato Gerador",
    jurisdiction: "Federal",
    authority: "Congresso Nacional",
    documentIdentifier: "LC 87/1996",
    article: "Art. 2º",
    text: "O imposto incide sobre: I - operações relativas à circulação de mercadorias, inclusive o fornecimento de alimentação e bebidas em bares, restaurantes e estabelecimentos similares; II - prestações de serviços de transporte intermunicipal e interestadual, por qualquer via, de pessoas, bens, mercadorias ou valores; III - prestações onerosas de serviços de comunicação.",
    effectiveDate: "1996-09-13",
    version: "1.0",
    validityStatus: "VIGENTE",
    topicIds: ["t_icms", "t_impostos_estaduais", "topico_icms"],
    subjectName: "Legislação Tributária",
    keywords: [
      "ICMS",
      "Lei Kandir",
      "LC 87/96",
      "circulação de mercadorias",
      "transporte intermunicipal",
      "comunicação",
    ],
    reliability: 1.0,
  },
];

/**
 * Retorna todas as fontes auditadas registradas no repositório nativo.
 */
export function getAllVerifiedLegalSources(): LegalSource[] {
  return [...VERIFIED_LEGAL_SOURCES_REPOSITORY];
}
