/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDisponibilidadeRouteImport } from './routes/_authenticated/disponibilidade'
import { Route as AuthenticatedDominioRouteImport } from './routes/_authenticated/dominio'
import { Route as AuthenticatedMateriasRouteImport } from './routes/_authenticated/materias'
import { Route as AuthenticatedCentralErrosIndexRouteImport } from './routes/_authenticated/central-erros/index'
import { Route as AuthenticatedCentralErrosErrorIdRouteImport } from './routes/_authenticated/central-erros/$errorId'
import { Route as AuthenticatedConcursosIndexRouteImport } from './routes/_authenticated/concursos/index'
import { Route as AuthenticatedConcursosContestIdRouteImport } from './routes/_authenticated/concursos/$contestId'
import { Route as AuthenticatedDiagnosticoIndexRouteImport } from './routes/_authenticated/diagnostico/index'
import { Route as AuthenticatedDiagnosticoTopicIdRouteImport } from './routes/_authenticated/diagnostico/$topicId'
import { Route as AuthenticatedPlanoIndexRouteImport } from './routes/_authenticated/plano/index'
import { Route as AuthenticatedPlanoPlanIdRouteImport } from './routes/_authenticated/plano/$planId'
import { Route as AuthenticatedRevisaoIndexRouteImport } from './routes/_authenticated/revisao/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisponibilidadeRoute =
  AuthenticatedDisponibilidadeRouteImport.update({
    id: '/disponibilidade',
    path: '/disponibilidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDominioRoute = AuthenticatedDominioRouteImport.update({
  id: '/dominio',
  path: '/dominio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMateriasRoute = AuthenticatedMateriasRouteImport.update({
  id: '/materias',
  path: '/materias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCentralErrosIndexRoute =
  AuthenticatedCentralErrosIndexRouteImport.update({
    id: '/central-erros/',
    path: '/central-erros/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCentralErrosErrorIdRoute =
  AuthenticatedCentralErrosErrorIdRouteImport.update({
    id: '/central-erros/$errorId',
    path: '/central-erros/$errorId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConcursosIndexRoute =
  AuthenticatedConcursosIndexRouteImport.update({
    id: '/concursos/',
    path: '/concursos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConcursosContestIdRoute =
  AuthenticatedConcursosContestIdRouteImport.update({
    id: '/concursos/$contestId',
    path: '/concursos/$contestId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiagnosticoIndexRoute =
  AuthenticatedDiagnosticoIndexRouteImport.update({
    id: '/diagnostico/',
    path: '/diagnostico/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiagnosticoTopicIdRoute =
  AuthenticatedDiagnosticoTopicIdRouteImport.update({
    id: '/diagnostico/$topicId',
    path: '/diagnostico/$topicId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanoIndexRoute = AuthenticatedPlanoIndexRouteImport.update({
  id: '/plano/',
  path: '/plano/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanoPlanIdRoute =
  AuthenticatedPlanoPlanIdRouteImport.update({
    id: '/plano/$planId',
    path: '/plano/$planId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRevisaoIndexRoute =
  AuthenticatedRevisaoIndexRouteImport.update({
    id: '/revisao/',
    path: '/revisao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disponibilidade': typeof AuthenticatedDisponibilidadeRoute
  '/dominio': typeof AuthenticatedDominioRoute
  '/materias': typeof AuthenticatedMateriasRoute
  '/central-erros/$errorId': typeof AuthenticatedCentralErrosErrorIdRoute
  '/concursos/$contestId': typeof AuthenticatedConcursosContestIdRoute
  '/diagnostico/$topicId': typeof AuthenticatedDiagnosticoTopicIdRoute
  '/plano/$planId': typeof AuthenticatedPlanoPlanIdRoute
  '/central-erros/': typeof AuthenticatedCentralErrosIndexRoute
  '/concursos/': typeof AuthenticatedConcursosIndexRoute
  '/diagnostico/': typeof AuthenticatedDiagnosticoIndexRoute
  '/plano/': typeof AuthenticatedPlanoIndexRoute
  '/revisao/': typeof AuthenticatedRevisaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disponibilidade': typeof AuthenticatedDisponibilidadeRoute
  '/dominio': typeof AuthenticatedDominioRoute
  '/materias': typeof AuthenticatedMateriasRoute
  '/central-erros/$errorId': typeof AuthenticatedCentralErrosErrorIdRoute
  '/concursos/$contestId': typeof AuthenticatedConcursosContestIdRoute
  '/diagnostico/$topicId': typeof AuthenticatedDiagnosticoTopicIdRoute
  '/plano/$planId': typeof AuthenticatedPlanoPlanIdRoute
  '/central-erros': typeof AuthenticatedCentralErrosIndexRoute
  '/concursos': typeof AuthenticatedConcursosIndexRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoIndexRoute
  '/plano': typeof AuthenticatedPlanoIndexRoute
  '/revisao': typeof AuthenticatedRevisaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/disponibilidade': typeof AuthenticatedDisponibilidadeRoute
  '/_authenticated/dominio': typeof AuthenticatedDominioRoute
  '/_authenticated/materias': typeof AuthenticatedMateriasRoute
  '/_authenticated/central-erros/$errorId': typeof AuthenticatedCentralErrosErrorIdRoute
  '/_authenticated/concursos/$contestId': typeof AuthenticatedConcursosContestIdRoute
  '/_authenticated/diagnostico/$topicId': typeof AuthenticatedDiagnosticoTopicIdRoute
  '/_authenticated/plano/$planId': typeof AuthenticatedPlanoPlanIdRoute
  '/_authenticated/central-erros/': typeof AuthenticatedCentralErrosIndexRoute
  '/_authenticated/concursos/': typeof AuthenticatedConcursosIndexRoute
  '/_authenticated/diagnostico/': typeof AuthenticatedDiagnosticoIndexRoute
  '/_authenticated/plano/': typeof AuthenticatedPlanoIndexRoute
  '/_authenticated/revisao/': typeof AuthenticatedRevisaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/nova-senha'
    | '/configuracoes'
    | '/dashboard'
    | '/disponibilidade'
    | '/dominio'
    | '/materias'
    | '/central-erros/$errorId'
    | '/concursos/$contestId'
    | '/diagnostico/$topicId'
    | '/plano/$planId'
    | '/central-erros/'
    | '/concursos/'
    | '/diagnostico/'
    | '/plano/'
    | '/revisao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/nova-senha'
    | '/configuracoes'
    | '/dashboard'
    | '/disponibilidade'
    | '/dominio'
    | '/materias'
    | '/central-erros/$errorId'
    | '/concursos/$contestId'
    | '/diagnostico/$topicId'
    | '/plano/$planId'
    | '/central-erros'
    | '/concursos'
    | '/diagnostico'
    | '/plano'
    | '/revisao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/nova-senha'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/disponibilidade'
    | '/_authenticated/dominio'
    | '/_authenticated/materias'
    | '/_authenticated/central-erros/$errorId'
    | '/_authenticated/concursos/$contestId'
    | '/_authenticated/diagnostico/$topicId'
    | '/_authenticated/plano/$planId'
    | '/_authenticated/central-erros/'
    | '/_authenticated/concursos/'
    | '/_authenticated/diagnostico/'
    | '/_authenticated/plano/'
    | '/_authenticated/revisao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disponibilidade': {
      id: '/_authenticated/disponibilidade'
      path: '/disponibilidade'
      fullPath: '/disponibilidade'
      preLoaderRoute: typeof AuthenticatedDisponibilidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dominio': {
      id: '/_authenticated/dominio'
      path: '/dominio'
      fullPath: '/dominio'
      preLoaderRoute: typeof AuthenticatedDominioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materias': {
      id: '/_authenticated/materias'
      path: '/materias'
      fullPath: '/materias'
      preLoaderRoute: typeof AuthenticatedMateriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/central-erros/': {
      id: '/_authenticated/central-erros/'
      path: '/central-erros'
      fullPath: '/central-erros/'
      preLoaderRoute: typeof AuthenticatedCentralErrosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/central-erros/$errorId': {
      id: '/_authenticated/central-erros/$errorId'
      path: '/central-erros/$errorId'
      fullPath: '/central-erros/$errorId'
      preLoaderRoute: typeof AuthenticatedCentralErrosErrorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concursos/': {
      id: '/_authenticated/concursos/'
      path: '/concursos'
      fullPath: '/concursos/'
      preLoaderRoute: typeof AuthenticatedConcursosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concursos/$contestId': {
      id: '/_authenticated/concursos/$contestId'
      path: '/concursos/$contestId'
      fullPath: '/concursos/$contestId'
      preLoaderRoute: typeof AuthenticatedConcursosContestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostico/': {
      id: '/_authenticated/diagnostico/'
      path: '/diagnostico'
      fullPath: '/diagnostico/'
      preLoaderRoute: typeof AuthenticatedDiagnosticoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostico/$topicId': {
      id: '/_authenticated/diagnostico/$topicId'
      path: '/diagnostico/$topicId'
      fullPath: '/diagnostico/$topicId'
      preLoaderRoute: typeof AuthenticatedDiagnosticoTopicIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plano/': {
      id: '/_authenticated/plano/'
      path: '/plano'
      fullPath: '/plano/'
      preLoaderRoute: typeof AuthenticatedPlanoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plano/$planId': {
      id: '/_authenticated/plano/$planId'
      path: '/plano/$planId'
      fullPath: '/plano/$planId'
      preLoaderRoute: typeof AuthenticatedPlanoPlanIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revisao/': {
      id: '/_authenticated/revisao/'
      path: '/revisao'
      fullPath: '/revisao/'
      preLoaderRoute: typeof AuthenticatedRevisaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisponibilidadeRoute: typeof AuthenticatedDisponibilidadeRoute
  AuthenticatedDominioRoute: typeof AuthenticatedDominioRoute
  AuthenticatedMateriasRoute: typeof AuthenticatedMateriasRoute
  AuthenticatedCentralErrosErrorIdRoute: typeof AuthenticatedCentralErrosErrorIdRoute
  AuthenticatedConcursosContestIdRoute: typeof AuthenticatedConcursosContestIdRoute
  AuthenticatedDiagnosticoTopicIdRoute: typeof AuthenticatedDiagnosticoTopicIdRoute
  AuthenticatedPlanoPlanIdRoute: typeof AuthenticatedPlanoPlanIdRoute
  AuthenticatedCentralErrosIndexRoute: typeof AuthenticatedCentralErrosIndexRoute
  AuthenticatedConcursosIndexRoute: typeof AuthenticatedConcursosIndexRoute
  AuthenticatedDiagnosticoIndexRoute: typeof AuthenticatedDiagnosticoIndexRoute
  AuthenticatedPlanoIndexRoute: typeof AuthenticatedPlanoIndexRoute
  AuthenticatedRevisaoIndexRoute: typeof AuthenticatedRevisaoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisponibilidadeRoute: AuthenticatedDisponibilidadeRoute,
  AuthenticatedDominioRoute: AuthenticatedDominioRoute,
  AuthenticatedMateriasRoute: AuthenticatedMateriasRoute,
  AuthenticatedCentralErrosErrorIdRoute: AuthenticatedCentralErrosErrorIdRoute,
  AuthenticatedConcursosContestIdRoute: AuthenticatedConcursosContestIdRoute,
  AuthenticatedDiagnosticoTopicIdRoute: AuthenticatedDiagnosticoTopicIdRoute,
  AuthenticatedPlanoPlanIdRoute: AuthenticatedPlanoPlanIdRoute,
  AuthenticatedCentralErrosIndexRoute: AuthenticatedCentralErrosIndexRoute,
  AuthenticatedConcursosIndexRoute: AuthenticatedConcursosIndexRoute,
  AuthenticatedDiagnosticoIndexRoute: AuthenticatedDiagnosticoIndexRoute,
  AuthenticatedPlanoIndexRoute: AuthenticatedPlanoIndexRoute,
  AuthenticatedRevisaoIndexRoute: AuthenticatedRevisaoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  NovaSenhaRoute: NovaSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
